# Site settings
title: James Cool - Programming and Web Development
email: jeffreysbrother@gmail.com
description: programming and web development
url: "http://jeffreysbrother.github.io/" # the base hostname & protocol for your site
twitter_username: jeffreysbrother
github_username: jeffreysbrother
npm_username: jeffreysbrother
treehouse_username: jamescool
linkedin_username: jmcool
paginate_path: "/text/page/:num"
paginate: 20
highlighter: rouge
sass:
  style: compressed

# Build settings
markdown: kramdown
permalink: /:title

# Gems
plugins: [jekyll-paginate, jekyll-gist]

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: James Cool
      layout: "post"
      category: Programming
      comments: true
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      author: James Cool
      layout: "post"
      category: Programming
